const products = [
  {
    id: "PRD001",
    name: "Classic White T-shirt",
    price: 150000,
    quantity: 50,
    type: "T-shirts",
    image: "images/tshirts/classic-white-tshirt.jpg",
  },
  {
    id: "PRD002",
    name: "Striped Polo Shirt",
    price: 180000,
    quantity: 45,
    type: "T-shirts",
    image: "images/tshirts/striped-polo-shirt.jpg",
  },
  {
    id: "PRD003",
    name: "Graphic Oversized Tee",
    price: 170000,
    quantity: 60,
    type: "T-shirts",
    image: "images/tshirts/graphic-oversized-tee.jpg",
  },
  {
    id: "PRD004",
    name: "Cotton V-neck Tee",
    price: 140000,
    quantity: 40,
    type: "T-shirts",
    image: "images/tshirts/cotton-v-neck-tee.jpg",
  },
  {
    id: "PRD005",
    name: "Black Crewneck Tee",
    price: 150000,
    quantity: 55,
    type: "T-shirts",
    image: "images/tshirts/black-crewneck-tee.jpg",
  },
  {
    id: "PRD006",
    name: "Vintage Print Tee",
    price: 160000,
    quantity: 35,
    type: "T-shirts",
    image: "images/tshirts/vintage-print-tee.jpg",
  },
  {
    id: "PRD007",
    name: "Slim Fit T-shirt",
    price: 145000,
    quantity: 25,
    type: "T-shirts",
    image: "images/tshirts/slim-fit-tshirt.jpg",
  },
  {
    id: "PRD008",
    name: "Long Sleeve T-shirt",
    price: 190000,
    quantity: 30,
    type: "T-shirts",
    image: "images/tshirts/long-sleeve-tshirt.jpg",
  },
  {
    id: "PRD009",
    name: "Basic Pocket Tee",
    price: 130000,
    quantity: 60,
    type: "T-shirts",
    image: "images/tshirts/basic-pocket-tee.jpg",
  },
  {
    id: "PRD010",
    name: "Heather Grey Tee",
    price: 140000,
    quantity: 48,
    type: "T-shirts",
    image: "images/tshirts/heather-grey-tee.jpg",
  },
  {
    id: "PRD011",
    name: "Blue Denim Shirt",
    price: 250000,
    quantity: 40,
    type: "Shirts",
    image: "images/shirts/blue-denim-shirt.jpg",
  },
  {
    id: "PRD012",
    name: "White Formal Shirt",
    price: 270000,
    quantity: 35,
    type: "Shirts",
    image: "images/shirts/white-formal-shirt.jpg",
  },
  {
    id: "PRD013",
    name: "Casual Checked Shirt",
    price: 240000,
    quantity: 50,
    type: "Shirts",
    image: "images/shirts/casual-checked-shirt.jpg",
  },
  {
    id: "PRD014",
    name: "Linen Beach Shirt",
    price: 300000,
    quantity: 20,
    type: "Shirts",
    image: "images/shirts/linen-beach-shirt.jpg",
  },
  {
    id: "PRD015",
    name: "Black Satin Shirt",
    price: 350000,
    quantity: 25,
    type: "Shirts",
    image: "images/shirts/black-satin-shirt.jpg",
  },
  {
    id: "PRD016",
    name: "Floral Print Shirt",
    price: 260000,
    quantity: 30,
    type: "Shirts",
    image: "images/shirts/floral-print-shirt.jpg",
  },
  {
    id: "PRD017",
    name: "Pink Oxford Shirt",
    price: 280000,
    quantity: 45,
    type: "Shirts",
    image: "images/shirts/pink-oxford-shirt.jpg",
  },
  {
    id: "PRD018",
    name: "Grey Slim Fit Shirt",
    price: 310000,
    quantity: 18,
    type: "Shirts",
    image: "images/shirts/grey-slim-fit-shirt.jpg",
  },
  {
    id: "PRD019",
    name: "Striped Office Shirt",
    price: 290000,
    quantity: 25,
    type: "Shirts",
    image: "images/shirts/striped-office-shirt.jpg",
  },
  {
    id: "PRD020",
    name: "Denim Snap Button Shirt",
    price: 320000,
    quantity: 20,
    type: "Shirts",
    image: "images/shirts/denim-snap-button-shirt.jpg",
  },
  {
    id: "PRD021",
    name: "Black Leather Jacket",
    price: 750000,
    quantity: 20,
    type: "Jackets",
    image: "images/jackets/black-leather-jacket.jpg",
  },
  {
    id: "PRD022",
    name: "Green Parka Jacket",
    price: 600000,
    quantity: 22,
    type: "Jackets",
    image: "images/jackets/green-parka-jacket.jpg",
  },
  {
    id: "PRD023",
    name: "Denim Trucker Jacket",
    price: 550000,
    quantity: 15,
    type: "Jackets",
    image: "images/jackets/denim-trucker-jacket.jpg",
  },
  {
    id: "PRD024",
    name: "Brown Suede Jacket",
    price: 850000,
    quantity: 10,
    type: "Jackets",
    image: "images/jackets/brown-suede-jacket.jpg",
  },
  {
    id: "PRD025",
    name: "Red Bomber Jacket",
    price: 680000,
    quantity: 18,
    type: "Jackets",
    image: "images/jackets/red-bomber-jacket.jpg",
  },
  {
    id: "PRD026",
    name: "Fleece Zip-up Jacket",
    price: 450000,
    quantity: 35,
    type: "Jackets",
    image: "images/jackets/fleece-zip-up-jacket.jpg",
  },
  {
    id: "PRD027",
    name: "Quilted Down Jacket",
    price: 950000,
    quantity: 12,
    type: "Jackets",
    image: "images/jackets/quilted-down-jacket.jpg",
  },
  {
    id: "PRD028",
    name: "Rainproof Windbreaker",
    price: 500000,
    quantity: 25,
    type: "Jackets",
    image: "images/jackets/rainproof-windbreaker.jpg",
  },
  {
    id: "PRD029",
    name: "Double-breasted Coat",
    price: 1200000,
    quantity: 8,
    type: "Jackets",
    image: "images/jackets/double-breasted-coat.jpg",
  },
  {
    id: "PRD030",
    name: "Navy Wool Blazer",
    price: 1100000,
    quantity: 5,
    type: "Jackets",
    image: "images/jackets/navy-wool-blazer.jpg",
  },
  {
    id: "PRD031",
    name: "Maxi Floral Dress",
    price: 750000,
    quantity: 18,
    type: "Dresses",
    image: "images/dresses/maxi-floral-dress.jpg",
  },
  {
    id: "PRD032",
    name: "Red Cocktail Dress",
    price: 850000,
    quantity: 15,
    type: "Dresses",
    image: "images/dresses/red-cocktail-dress.jpg",
  },
  {
    id: "PRD033",
    name: "Black Sheath Dress",
    price: 900000,
    quantity: 20,
    type: "Dresses",
    image: "images/dresses/black-sheath-dress.jpg",
  },
  {
    id: "PRD034",
    name: "Casual Summer Dress",
    price: 550000,
    quantity: 25,
    type: "Dresses",
    image: "images/dresses/casual-summer-dress.jpg",
  },
  {
    id: "PRD035",
    name: "Long Sleeve Evening Dress",
    price: 1200000,
    quantity: 10,
    type: "Dresses",
    image: "images/dresses/long-sleeve-evening-dress.jpg",
  },
  {
    id: "PRD036",
    name: "A-line Wedding Dress",
    price: 2500000,
    quantity: 5,
    type: "Dresses",
    image: "images/dresses/a-line-wedding-dress.jpg",
  },
  {
    id: "PRD037",
    name: "Striped Mini Dress",
    price: 400000,
    quantity: 30,
    type: "Dresses",
    image: "images/dresses/striped-mini-dress.jpg",
  },
  {
    id: "PRD038",
    name: "Plaid Pencil Skirt",
    price: 300000,
    quantity: 40,
    type: "Skirts",
    image: "images/skirts/plaid-pencil-skirt.jpg",
  },
  {
    id: "PRD039",
    name: "Denim A-line Skirt",
    price: 350000,
    quantity: 20,
    type: "Skirts",
    image: "images/skirts/denim-a-line-skirt.jpg",
  },
  {
    id: "PRD040",
    name: "Leather Mini Skirt",
    price: 400000,
    quantity: 30,
    type: "Skirts",
    image: "images/skirts/leather-mini-skirt.jpg",
  },
  {
    id: "PRD041",
    name: "High-waisted Pleated Skirt",
    price: 500000,
    quantity: 18,
    type: "Skirts",
    image: "images/skirts/high-waisted-pleated-skirt.jpg",
  },
  {
    id: "PRD042",
    name: "Tulle Midi Skirt",
    price: 600000,
    quantity: 25,
    type: "Skirts",
    image: "images/skirts/tulle-midi-skirt.jpg",
  },
  {
    id: "PRD043",
    name: "Black Satin Skirt",
    price: 700000,
    quantity: 12,
    type: "Skirts",
    image: "images/skirts/black-satin-skirt.jpg",
  },
  {
    id: "PRD044",
    name: "Floral Wrap Skirt",
    price: 550000,
    quantity: 28,
    type: "Skirts",
    image: "images/skirts/floral-wrap-skirt.jpg",
  },
  {
    id: "PRD045",
    name: "Tartan Check Skirt",
    price: 320000,
    quantity: 35,
    type: "Skirts",
    image: "images/skirts/tartan-check-skirt.jpg",
  },
  {
    id: "PRD046",
    name: "Chunky White Sneakers",
    price: 500000,
    quantity: 40,
    type: "Shoes",
    image: "images/shoes/chunky-white-sneakers.jpg",
  },
  {
    id: "PRD047",
    name: "Black Ankle Boots",
    price: 600000,
    quantity: 25,
    type: "Shoes",
    image: "images/shoes/black-ankle-boots.jpg",
  },
  {
    id: "PRD048",
    name: "Leather Loafers",
    price: 700000,
    quantity: 30,
    type: "Shoes",
    image: "images/shoes/leather-loafers.jpg",
  },
  {
    id: "PRD049",
    name: "Red Heels",
    price: 800000,
    quantity: 20,
    type: "Shoes",
    image: "images/shoes/red-heels.jpg",
  },
  {
    id: "PRD050",
    name: "White Sneakers",
    price: 450000,
    quantity: 50,
    type: "Shoes",
    image: "images/shoes/white-sneakers.jpg",
  },
];

export { products };
