const getProducts = [
  {
    id: "PRD001",
    name: "Classic White T-shirt",
    price: 150000,
    quantity: 50,
    type: "T-shirts",
    status: "Ready",
    image: "images/tshirts/classic-white-tshirt.jpg",
    rating: 4.5,
    reviewer: 300,
  },
  {
    id: "PRD002",
    name: "Striped Polo Shirt",
    price: 180000,
    quantity: 45,
    type: "T-shirts",
    status: "Ready",
    image: "images/tshirts/striped-polo-shirt.jpg",
    rating: 4.6,
    reviewer: 250,
  },
  {
    id: "PRD003",
    name: "Graphic Oversized Tee",
    price: 170000,
    quantity: 60,
    type: "T-shirts",
    status: "Ready",
    image: "images/tshirts/graphic-oversized-tee.jpg",
    rating: 4.7,
    reviewer: 400,
  },
  {
    id: "PRD004",
    name: "Cotton V-neck Tee",
    price: 140000,
    quantity: 40,
    type: "T-shirts",
    status: "Ready",
    image: "images/tshirts/cotton-v-neck-tee.jpg",
    rating: 4.4,
    reviewer: 180,
  },
  {
    id: "PRD005",
    name: "Black Crewneck Tee",
    price: 150000,
    quantity: 55,
    type: "T-shirts",
    status: "Ready",
    image: "images/tshirts/black-crewneck-tee.jpg",
    rating: 4.5,
    reviewer: 320,
  },
  {
    id: "PRD006",
    name: "Vintage Print Tee",
    price: 160000,
    quantity: 35,
    type: "T-shirts",
    status: "Ready",
    image: "images/tshirts/vintage-print-tee.jpg",
    rating: 4.3,
    reviewer: 190,
  },
  {
    id: "PRD007",
    name: "Slim Fit T-shirt",
    price: 145000,
    quantity: 25,
    type: "T-shirts",
    status: "Pending",
    image: "images/tshirts/slim-fit-tshirt.jpg",
    rating: 4.2,
    reviewer: 150,
  },
  {
    id: "PRD008",
    name: "Long Sleeve T-shirt",
    price: 190000,
    quantity: 30,
    type: "T-shirts",
    status: "Pending",
    image: "images/tshirts/long-sleeve-tshirt.jpg",
    rating: 4.6,
    reviewer: 210,
  },
  {
    id: "PRD009",
    name: "Basic Pocket Tee",
    price: 130000,
    quantity: 60,
    type: "T-shirts",
    status: "Pending",
    image: "images/tshirts/basic-pocket-tee.jpg",
    rating: 4.2,
    reviewer: 170,
  },
  {
    id: "PRD010",
    name: "Heather Grey Tee",
    price: 140000,
    quantity: 48,
    type: "T-shirts",
    status: "Pending",
    image: "images/tshirts/heather-grey-tee.jpg",
    rating: 4.3,
    reviewer: 160,
  },
  {
    id: "PRD011",
    name: "Blue Denim Shirt",
    price: 250000,
    quantity: 40,
    type: "Shirts",
    status: "Pending",
    image: "images/shirts/blue-denim-shirt.jpg",
    rating: 4.7,
    reviewer: 280,
  },
  {
    id: "PRD012",
    name: "White Formal Shirt",
    price: 270000,
    quantity: 35,
    type: "Shirts",
    status: "Pending",
    image: "images/shirts/white-formal-shirt.jpg",
    rating: 4.8,
    reviewer: 320,
  },
  {
    id: "PRD013",
    name: "Casual Checked Shirt",
    price: 240000,
    quantity: 0,
    type: "Shirts",
    status: "Soldout",
    image: "images/shirts/casual-checked-shirt.jpg",
    rating: 4.6,
    reviewer: 200,
  },
  {
    id: "PRD014",
    name: "Linen Beach Shirt",
    price: 300000,
    quantity: 0,
    type: "Shirts",
    status: "Soldout",
    image: "images/shirts/linen-beach-shirt.jpg",
    rating: 4.5,
    reviewer: 150,
  },
  {
    id: "PRD015",
    name: "Black Satin Shirt",
    price: 350000,
    quantity: 0,
    type: "Shirts",
    status: "Soldout",
    image: "images/shirts/black-satin-shirt.jpg",
    rating: 4.7,
    reviewer: 240,
  },
  {
    id: "PRD016",
    name: "Slim Fit Formal Shirt",
    price: 280000,
    quantity: 0,
    type: "Shirts",
    status: "Soldout",
    image: "images/shirts/slim-fit-formal-shirt.jpg",
    rating: 4.6,
    reviewer: 180,
  },
  {
    id: "PRD017",
    name: "Casual Plaid Shirt",
    price: 260000,
    quantity: 20,
    type: "Shirts",
    status: "Pending",
    image: "images/shirts/casual-plaid-shirt.jpg",
    rating: 4.4,
    reviewer: 140,
  },
  {
    id: "PRD018",
    name: "Brown Leather Jacket",
    price: 500000,
    quantity: 10,
    type: "Jackets",
    status: "Ready",
    image: "images/jackets/brown-leather-jacket.jpg",
    rating: 4.8,
    reviewer: 300,
  },
  {
    id: "PRD019",
    name: "Black Bomber Jacket",
    price: 450000,
    quantity: 15,
    type: "Jackets",
    status: "Ready",
    image: "images/jackets/black-bomber-jacket.jpg",
    rating: 4.7,
    reviewer: 280,
  },
  {
    id: "PRD020",
    name: "Parka Winter Coat",
    price: 600000,
    quantity: 5,
    type: "Jackets",
    status: "Ready",
    image: "images/jackets/parka-winter-coat.jpg",
    rating: 4.9,
    reviewer: 350,
  },
  {
    id: "PRD021",
    name: "Grey Hoodie",
    price: 200000,
    quantity: 25,
    type: "Hoodies",
    status: "Pending",
    image: "images/hoodies/grey-hoodie.jpg",
    rating: 4.5,
    reviewer: 190,
  },
  {
    id: "PRD022",
    name: "Black Zipper Hoodie",
    price: 220000,
    quantity: 30,
    type: "Hoodies",
    status: "Ready",
    image: "images/hoodies/black-zipper-hoodie.jpg",
    rating: 4.6,
    reviewer: 210,
  },
  {
    id: "PRD023",
    name: "Navy Pullover Hoodie",
    price: 230000,
    quantity: 35,
    type: "Hoodies",
    status: "Ready",
    image: "images/hoodies/navy-pullover-hoodie.jpg",
    rating: 4.7,
    reviewer: 220,
  },
  {
    id: "PRD024",
    name: "Green Cargo Pants",
    price: 300000,
    quantity: 20,
    type: "Pants",
    status: "Ready",
    image: "images/pants/green-cargo-pants.jpg",
    rating: 4.8,
    reviewer: 250,
  },
  {
    id: "PRD025",
    name: "Blue Jeans",
    price: 280000,
    quantity: 50,
    type: "Pants",
    status: "Ready",
    image: "images/pants/blue-jeans.jpg",
    rating: 4.7,
    reviewer: 300,
  },
  {
    id: "PRD026",
    name: "Slim Fit Trousers",
    price: 320000,
    quantity: 15,
    type: "Pants",
    status: "Pending",
    image: "images/pants/slim-fit-trousers.jpg",
    rating: 4.6,
    reviewer: 200,
  },
  {
    id: "PRD027",
    name: "Chino Shorts",
    price: 180000,
    quantity: 40,
    type: "Shorts",
    status: "Ready",
    image: "images/shorts/chino-shorts.jpg",
    rating: 4.5,
    reviewer: 150,
  },
  {
    id: "PRD028",
    name: "Denim Shorts",
    price: 200000,
    quantity: 35,
    type: "Shorts",
    status: "Ready",
    image: "images/shorts/denim-shorts.jpg",
    rating: 4.4,
    reviewer: 170,
  },
  {
    id: "PRD029",
    name: "Basic Gym Shorts",
    price: 150000,
    quantity: 60,
    type: "Shorts",
    status: "Ready",
    image: "images/shorts/basic-gym-shorts.jpg",
    rating: 4.3,
    reviewer: 130,
  },
  {
    id: "PRD030",
    name: "Sports Joggers",
    price: 250000,
    quantity: 25,
    type: "Pants",
    status: "Pending",
    image: "images/pants/sports-joggers.jpg",
    rating: 4.6,
    reviewer: 220,
  },
  {
    id: "PRD031",
    name: "Classic Trench Coat",
    price: 700000,
    quantity: 8,
    type: "Jackets",
    status: "Ready",
    image: "images/jackets/classic-trench-coat.jpg",
    rating: 4.9,
    reviewer: 320,
  },
  {
    id: "PRD032",
    name: "Denim Jacket",
    price: 400000,
    quantity: 18,
    type: "Jackets",
    status: "Pending",
    image: "images/jackets/denim-jacket.jpg",
    rating: 4.7,
    reviewer: 250,
  },
  {
    id: "PRD033",
    name: "Basic White T-Shirt",
    price: 120000,
    quantity: 70,
    type: "T-Shirts",
    status: "Ready",
    image: "images/tshirts/basic-white-tshirt.jpg",
    rating: 4.5,
    reviewer: 200,
  },
  {
    id: "PRD034",
    name: "Graphic Print T-Shirt",
    price: 140000,
    quantity: 60,
    type: "T-Shirts",
    status: "Ready",
    image: "images/tshirts/graphic-print-tshirt.jpg",
    rating: 4.6,
    reviewer: 180,
  },
  {
    id: "PRD035",
    name: "Oversized Hoodie",
    price: 230000,
    quantity: 20,
    type: "Hoodies",
    status: "Pending",
    image: "images/hoodies/oversized-hoodie.jpg",
    rating: 4.7,
    reviewer: 210,
  },
  {
    id: "PRD036",
    name: "Floral Summer Shirt",
    price: 260000,
    quantity: 15,
    type: "Shirts",
    status: "Ready",
    image: "images/shirts/floral-summer-shirt.jpg",
    rating: 4.6,
    reviewer: 160,
  },
  {
    id: "PRD037",
    name: "Cotton Chino Pants",
    price: 300000,
    quantity: 30,
    type: "Pants",
    status: "Ready",
    image: "images/pants/cotton-chino-pants.jpg",
    rating: 4.8,
    reviewer: 240,
  },
  {
    id: "PRD038",
    name: "Lightweight Puffer Jacket",
    price: 550000,
    quantity: 12,
    type: "Jackets",
    status: "Ready",
    image: "images/jackets/lightweight-puffer-jacket.jpg",
    rating: 4.8,
    reviewer: 310,
  },
  {
    id: "PRD039",
    name: "Casual Khaki Shorts",
    price: 200000,
    quantity: 40,
    type: "Shorts",
    status: "Ready",
    image: "images/shorts/casual-khaki-shorts.jpg",
    rating: 4.5,
    reviewer: 140,
  },
  {
    id: "PRD040",
    name: "Ribbed Knit Sweater",
    price: 350000,
    quantity: 10,
    type: "Sweaters",
    status: "Ready",
    image: "images/sweaters/ribbed-knit-sweater.jpg",
    rating: 4.9,
    reviewer: 280,
  },
  {
    id: "PRD041",
    name: "Striped Polo Shirt",
    price: 180000,
    quantity: 25,
    type: "Shirts",
    status: "Pending",
    image: "images/shirts/striped-polo-shirt.jpg",
    rating: 4.6,
    reviewer: 150,
  },
  {
    id: "PRD042",
    name: "Classic Beanie Hat",
    price: 100000,
    quantity: 50,
    type: "Accessories",
    status: "Ready",
    image: "images/accessories/classic-beanie-hat.jpg",
    rating: 4.7,
    reviewer: 100,
  },
  {
    id: "PRD043",
    name: "Leather Gloves",
    price: 180000,
    quantity: 20,
    type: "Accessories",
    status: "Ready",
    image: "images/accessories/leather-gloves.jpg",
    rating: 4.8,
    reviewer: 120,
  },
  {
    id: "PRD044",
    name: "Wool Scarf",
    price: 150000,
    quantity: 30,
    type: "Accessories",
    status: "Ready",
    image: "images/accessories/wool-scarf.jpg",
    rating: 4.6,
    reviewer: 110,
  },
  {
    id: "PRD045",
    name: "Sports Cap",
    price: 120000,
    quantity: 40,
    type: "Accessories",
    status: "Ready",
    image: "images/accessories/sports-cap.jpg",
    rating: 4.5,
    reviewer: 130,
  },
  {
    id: "PRD046",
    name: "Casual Canvas Sneakers",
    price: 350000,
    quantity: 25,
    type: "Shoes",
    status: "Ready",
    image: "images/shoes/casual-canvas-sneakers.jpg",
    rating: 4.8,
    reviewer: 210,
  },
  {
    id: "PRD047",
    name: "Leather Belt",
    price: 150000,
    quantity: 35,
    type: "Accessories",
    status: "Ready",
    image: "images/accessories/leather-belt.jpg",
    rating: 4.7,
    reviewer: 140,
  },
  {
    id: "PRD048",
    name: "Slim Fit Jeans",
    price: 300000,
    quantity: 20,
    type: "Pants",
    status: "Ready",
    image: "images/pants/slim-fit-jeans.jpg",
    rating: 4.6,
    reviewer: 190,
  },
  {
    id: "PRD049",
    name: "Wool Overcoat",
    price: 750000,
    quantity: 8,
    type: "Jackets",
    status: "Ready",
    image: "images/jackets/wool-overcoat.jpg",
    rating: 4.9,
    reviewer: 320,
  },
  {
    id: "PRD050",
    name: "Sports Joggers",
    price: 250000,
    quantity: 30,
    type: "Pants",
    status: "Ready",
    image: "images/pants/sports-joggers.jpg",
    rating: 4.8,
    reviewer: 220,
  },
];

export { getProducts };